name: SSN.Gererator - Nuget publishing

on:
  push:
    branches: [ main ]
    # tags:
    # - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: DotNet setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --configuration Release /p:Version=0.1.0
      working-directory: src
    # TODO: RESTORE ME! 
    # - name: Test
    #   run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    #   working-directory: src
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output .
      working-directory: src/SSN.Generator
    - name: Push
      run: dotnet nuget push Toloymak.SSN.Generator.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
      working-directory: src/SSN.Generator
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
